#!/bin/sh
sudo apt install fd-find build-essential git vim xclip npm nodejs ripgrep tree ninja-build gettext cmake unzip curl htop python3-pip
pip install -U robotframework-robocop --break-system-packages
npm install @microsoft/compose-language-service dockerfile-language-server-nodejs
git config --global core.editor "nvim"
ln -s $(which fdfind) ~/.local/bin/fd
