
return {
    {'marko-cerovac/material.nvim'},
    {'luisiacc/gruvbox-baby'},
    {'catppuccin/nvim'},
    {'sainnhe/gruvbox-material'},
    {'shaunsingh/nord.nvim'},
    {'sho-87/kanagawa-paper.nvim'},
    {'rebelot/kanagawa.nvim'},
    {'briones-gabriel/darcula-solid.nvim'},
    {'rktjmp/lush.nvim'},
    {'xero/miasma.nvim'},
    {'kvrohit/substrata.nvim'},
    {'lmburns/kimbox'},
    {'lewpoly/sherbet.nvim'},
    {'hardselius/warlock'},
    {'gmr458/cold.nvim'},
    {'ribru17/bamboo.nvim'},
    {'eldritch-theme/eldritch.nvim'},
}
