# alacritty.toml
# commented lines are the defaults
# man 5 alacritty (>0.13) for full config manual

import = [
"~/.config/alacritty/themes/nord.toml",
]

[font]
size = 10.0
offset = { x = 0, y = -2 }
glyph_offset = { x = 0, y = -1 }

[font.bold]
family = "RobotoMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "RobotoMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "RobotoMono Nerd Font"
style = "Italic"

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[env]
term ="xterm-256color"
